#docker-compose.yml
services:
  #Serviço da aplicação FastAPI
  api:
    build: . #Constroi a imagem a partir do Dockerfile na raiz do projeto
    container_name: api-gestao-escolar #Nome do container
    ports:
      - "8000:8000" #Mapeia a porta 8000 do host para a porta 8000 do container de acordo com o arquivo Dockerfile
    volumes:
      - .:/app #Monta o diretório atual em /app dentro do computador ->  as mudanças feitas no código fonte são refletidas automaticamente no container devido ao --reload do uvicorn
